# fly.toml app configuration file generated for fuji-jito on 2024-06-22T17:50:40+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fuji-jito'
primary_region = 'ams'

[build]
[build.args]
GO_VERSION = '1.22.2'

[env]
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = false
min_machines_running = 2
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
